<img align="right" src="https://ds-cs-images.s3.ap-northeast-2.amazonaws.com/Codestates_Fulllogo_Color.png" width=100>

## *DATA SCIENCE / SECTION 2 / SPRINT 3 / NOTE 2*

# üìù Assignment
---
# Data Wrangling

In [50]:
import pandas as pd

df = pd.read_csv('Lol_matchs.csv', index_col = 0)
team1 = df.iloc[:, :150]
team2 = df.iloc[:, 150:300]
result = df.iloc[:, 300:]

target = 'Team1'

df.head()

   Aatrox  Ahri  Akali  Alistar  Amumu  ...  Zilean.1  Zoe.1  Zyra.1  Team1  Team2
0     1.0   0.0    0.0      0.0    0.0  ...       0.0    0.0     0.0    1.0    0.0
1     0.0   0.0    0.0      0.0    0.0  ...       0.0    0.0     0.0    1.0    0.0
2     0.0   0.0    0.0      0.0    0.0  ...       0.0    0.0     0.0    1.0    0.0
3     0.0   0.0    0.0      0.0    0.0  ...       0.0    0.0     0.0    1.0    0.0
4     0.0   0.0    0.0      0.0    0.0  ...       0.0    0.0     0.0    1.0    0.0

[5 rows x 302 columns]

### 1) ÏßÄÏÜçÏ†ÅÏúºÎ°ú Ïó¨Îü¨Î∂ÑÏùò Ìè¨Ìä∏Ìè¥Î¶¨Ïò§ Îç∞Ïù¥ÌÑ∞Î•º Îû≠Í∏ÄÎßÅ ÌïòÏÑ∏Ïöî
- Ïó¨Îü¨Î∂ÑÏù¥ ÏÑ†ÌÉùÌïú Îç∞Ïù¥ÌÑ∞Îì§ÏùÑ Îû≠Í∏ÄÎßÅÌïòÏó¨ Î™®Îç∏ÏùÑ ÎßåÎì§Í∏∞ ÏúÑÌïú ÌÖåÏù¥Î∏î ÌòïÌÉúÏùò Îç∞Ïù¥ÌÑ∞Î°ú ÎßåÎì§Ïñ¥ Î≥¥ÏÑ∏Ïöî.
- **Îã§Ïùå Ìï®ÏàòÏùò resultÎ•º ÏôÑÏÑ±ÏãúÌÇ§Í≥† Î¶¨ÌÑ¥Í∞íÏùÑ Í≥ºÏ†ú Ï†úÏ∂úÌèºÏóê Ï†úÏ∂úÌïòÏÑ∏Ïöî.**

Í∞ÄÏ†∏Ïò® Îç∞Ïù¥ÌÑ∞Í∞Ä Ïù∏ÏΩîÎî©ÍπåÏßÄ Îã§ ÎêòÏñ¥ ÏûàÏñ¥ÏÑú, Îî∞Î°ú Îû≠Í∏ÄÎßÅ Ìï†ÎßåÌïúÍ≤å ÏóÜÎã§.. „Ö†„Ö†
Îã§ÏùåÏóî Îã§Î•∏ Îç∞Ïù¥ÌÑ∞Î•º Í∞ÄÏ†∏ÏôÄÏÑú ÏãúÎèÑÌï¥Î≥ºÍπå ÏÉùÍ∞Å Ï§ëÏûÖÎãàÎã§.

In [3]:
### Ïù¥Í≥≥ÏóêÏÑú Ï†úÏ∂úÌèº Í≥ºÏ†úÎ•º ÏßÑÌñâÌï¥ Ï£ºÏÑ∏Ïöî ###
import pandas as pd
df = pd.read_csv("https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/assignments/purchase_data.csv", sep=",",index_col=0)

## Îã§Ïùå result Ìï®Ïàò ÏïàÏóê male, female Î≥ÄÏàòÎ•º Í≥ÑÏÇ∞ÌïòÏÑ∏Ïöî.(groupby, get_groupÏùÑ ÏÇ¨Ïö©ÌïòÏÑ∏Ïöî.)
## sum_male: Age = 20, Gender = "Male" Í∑∏Î£πÏùò PriceÎ•º Ìï©ÌïòÏÑ∏Ïöî.
## sum_female: Age = 20, Gender = "Female" Í∑∏Î£πÏùò PriceÎ•º Ìï©ÌïòÏÑ∏Ïöî.

# def result(df):

#     sum_male = ###Ïù¥ Î∂ÄÎ∂ÑÏùÑ ÏôÑÏÑ±ÌïòÏÑ∏Ïöî###
#     sum_female = ###Ïù¥ Î∂ÄÎ∂ÑÏùÑ ÏôÑÏÑ±ÌïòÏÑ∏Ïöî###

#     print("sum_male: {}, sum_female: {}".format(sum_male, sum_female))
#     return round(sum_male + sum_female)

# result(df)
df

                        SN  ...  Price
Purchase ID                 ...
0                  Lisim78  ...   3.53
1              Lisovynya38  ...   1.56
2               Ithergue48  ...   4.88
3            Chamassasya86  ...   3.27
4                Iskosia90  ...   1.44
...                    ...  ...    ...
775             Aethedru70  ...   3.54
776                 Iral74  ...   1.63
777             Yathecal72  ...   3.46
778                Sisur91  ...   4.19
779              Ennrian78  ...   4.60

[780 rows x 6 columns]

In [4]:
df[(df.Age == 20)&(df.Gender == 'Male')].groupby(['Gender', 'Age'])['Price'].sum()

Gender  Age
Male    20     260.2
Name: Price, dtype: float64

In [5]:
df[(df.Age == 20)&(df.Gender == 'Female')].groupby(['Gender', 'Age'])['Price'].sum()

Gender  Age
Female  20     43.73
Name: Price, dtype: float64

In [6]:
def result(df):

    sum_male = df[(df.Age == 20)&(df.Gender == 'Male')].groupby(['Gender', 'Age'])['Price'].sum()[0]
    sum_female = df[(df.Age == 20)&(df.Gender == 'Female')].groupby(['Gender', 'Age'])['Price'].sum()[0]

    print("sum_male: {}, sum_female: {}".format(sum_male, sum_female))
    return round(sum_male + sum_female)

result(df)

sum_male: 260.20000000000005, sum_female: 43.730000000000004

304

### 2) ÏÉàÎ°ú ÌäπÏßïÎì§ÏùÑ ÎßåÎì§Ïñ¥ Î≥¥ÏÑ∏Ïöî
- Ïó¨Îü¨Î∂ÑÏù¥ ÏÑ†ÌÉùÌïú Îç∞Ïù¥ÌÑ∞ÏóêÏÑú ÌäπÏßï Í≥µÌïôÏùÑ ÏàòÌñâÌï¥ Î≥¥ÏÑ∏Ïöî.
- **(Îã§Ï§ëÏÑ†ÌÉù) purchase_dataÎ•º Îû≠Í∏ÄÎßÅÌïòÏó¨ Îã§Ïùå Ï°∞Í±¥ÏùÑ Í≥ÑÏÇ∞ÌïòÍ≥† Í≤∞Í≥ºÍ∞Ä Ïò¨Î∞îÎ•∏ Ìï≠Î™©Îßå Í≥ºÏ†ú Ï†úÏ∂úÌèºÏóê Ï†úÏ∂úÌïòÏÑ∏Ïöî.**
    1. ÎÇòÏù¥ 1-20ÏÑ∏ Í∑∏Î£π(20ÏÑ∏ Ìè¨Ìï®)Ïùò ÌèâÍ∑† PriceÎäî 3.101818Ïù¥Îã§.
    2. ÎÇòÏù¥ 21-50ÏÑ∏ Í∑∏Î£πÏùò ÌèâÍ∑† PriceÎäî 3.021559Ïù¥Îã§.
    3. Í∞ÄÏû• ÎßéÏù¥ Íµ¨ÏûÖÌïú ÏïÑÏù¥ÌÖúÏùò IDÎäî 178 Ïù¥Îã§.
    4. ÎëêÎ≤àÏß∏Î°ú Îß§Ï∂úÏùÑ ÎßéÏù¥ ÎÇ∏ ÏïÑÏù¥ÌÖú IDÎäî 145Ïù¥Îã§.

„Ö†„Ö†.. ÌäπÏßï Í≥µÌïô Ìï† Í≤ÉÎèÑ ÏóÜÎã§....

In [47]:
### Ïù¥Í≥≥ÏóêÏÑú Ï†úÏ∂úÌèº Í≥ºÏ†úÎ•º ÏßÑÌñâÌï¥ Ï£ºÏÑ∏Ïöî ###
# Í∑∏Î£πÎ≥Ñ Price ÌèâÍ∑†
print('Í∑∏Î£πÎ≥Ñ Price ÌèâÍ∑† 20ÏÑ∏ Ïù¥Ìïò : {}, 21ÏÑ∏ Ïù¥ÏÉÅ 50ÏÑ∏ Ïù¥Ìïò : {}'.format(round(df[df.Age <= 20].Price.mean(), 6), round(df[(df.Age >= 21)&(df.Age <= 50)].Price.mean(), 6)))
# ÌåêÎß§Ïàò ÏÉÅÏúÑ Item ID
print('Í∞ÄÏû• ÎßéÏù¥ Íµ¨ÏûÖÌïú ÏïÑÏù¥ÌÖú ID :', df['Item ID'].value_counts()[df['Item ID'].value_counts() == df['Item ID'].value_counts().max()].index[0])
# Ïã§Ïàò!!;;; ÎëêÎ≤àÏß∏Î°ú ÎßéÏù¥ ÌåêÎß§Ìïú Item ID
tem = df['Item ID'].value_counts()[df['Item ID'].value_counts() == df['Item ID'].value_counts()].sort_values(ascending = False).unique()[1]
print('ÎëêÎ≤àÏß∏Î°ú ÎßéÏù¥ Íµ¨ÏûÖÌïú ÏïÑÏù¥ÌÖú ID :', list(df['Item ID'].value_counts()[df['Item ID'].value_counts() == tem].index))
# Îß§Ï∂ú ÏÉÅÏúÑ Item IDs
print('ÎëêÎ≤àÏ®∞Î°ú Îß§Ï∂úÏùÑ ÎßéÏù¥ ÎÇ∏ ÏïÑÏù¥ÌÖú ID :', df.groupby('Item ID')['Price'].sum().sort_values(ascending = False).index[1])

Í∑∏Î£πÎ≥Ñ Price ÌèâÍ∑† 20ÏÑ∏ Ïù¥Ìïò : 3.101818, 21ÏÑ∏ Ïù¥ÏÉÅ 50ÏÑ∏ Ïù¥Ìïò : 3.021559
Í∞ÄÏû• ÎßéÏù¥ Íµ¨ÏûÖÌïú ÏïÑÏù¥ÌÖú ID : 178
ÎëêÎ≤àÏß∏Î°ú ÎßéÏù¥ Íµ¨ÏûÖÌïú ÏïÑÏù¥ÌÖú ID : [82, 108, 145]
ÎëêÎ≤àÏ®∞Î°ú Îß§Ï∂úÏùÑ ÎßéÏù¥ ÎÇ∏ ÏïÑÏù¥ÌÖú ID : 82

## üî• ÎèÑÏ†ÑÍ≥ºÏ†ú

### 3) Ï°∞Í∏à Î∂ÄÏ°±ÌïòÎçîÎùºÎèÑ ÏµúÏÜåÌïúÏùò Îû≠Í∏ÄÎßÅÏúºÎ°ú Îç∞Ïù¥ÌÑ∞Î•º Ï§ÄÎπÑÌïòÏó¨ Í∞ÑÎã®Ìïú Î™®Îç∏ÏùÑ ÌïôÏäµÏãúÏºú Î≥¥ÏÑ∏Ïöî
- Ïó¨Îü¨Î∂ÑÎì§Ïù¥ ÏÑ†ÌÉùÌïú Îç∞Ïù¥ÌÑ∞Î•º Í∞ÄÏßÄÍ≥† Í∞ÑÎã®Ìïú Î™®Îç∏ÏùÑ ÌïôÏäµÌïòÍ≥† Í≤∞Í≥ºÎ•º Î¶¨Ìè¨ÌåÖ Ìï©ÎãàÎã§.

0Ïùò Í∞íÏù¥ ÎßéÎã§. 300Í∞úÏ§ëÏóê 10Í∞úÎßå 1Ïù¥Í≥† ÎÇòÎ®∏ÏßÄ 290Í∞úÍ∞Ä 0Ïù¥Îùº ÏòàÏ∏°Í≤∞Í≥ºÍ∞Ä Ï¢ãÏßÄ ÏïäÏùÄ Í≤É Í∞ôÎã§. Ïù¥ÎØ∏ onehotÏù¥ ÎêòÏñ¥ ÏûàÏúºÎãà encoder ÏÇ¨Ïö© ÏïàÌïòÍ≥† Ïã§Ìñâ Ìï¥Î¥êÏïºÍ≤†Îã§.

In [53]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(df.iloc[:, :301], train_size=0.80, test_size=0.20, 
                                        stratify=df.Team1, random_state=2)

train_data, val_data = train_test_split(train_data, train_size=0.80, test_size=0.20, 
                                        stratify=train_data.Team1, random_state=2)

X_train = train_data.drop(target, axis = 1)
y_train = train_data[target]

X_val = val_data.drop(target, axis = 1)
y_val = val_data[target]

X_test = test_data.drop(target, axis = 1)
y_test = test_data[target]

X_train.shape, X_val.shape, X_test.shape

from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform
import numpy as np

pipe = make_pipeline(
    RandomForestRegressor(random_state=2)
)

dists = {
    'randomforestregressor__n_estimators': randint(50, 500), 
    'randomforestregressor__max_depth': [5, 10, 15, 20, None], 
    'randomforestregressor__max_features': uniform(0, 1) # max_features
}

clf = RandomizedSearchCV(
    pipe, 
    param_distributions=dists, 
    n_iter=50, 
    cv=2,
    scoring='neg_mean_absolute_error',  
    verbose=1,
    n_jobs=-1
)

clf.fit(X_train, y_train);

Fitting 2 folds for each of 50 candidates, totalling 100 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed: 16.0min
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed: 37.1min finished

In [54]:
pd.DataFrame(clf.cv_results_).sort_values(by='rank_test_score').T

                                                                                          3   ...                                                 22
mean_fit_time                                                                        37.4244  ...                                            4.96911
std_fit_time                                                                        0.187039  ...                                           0.057354
mean_score_time                                                                     0.476797  ...                                           0.163416
std_score_time                                                                     0.0618726  ...                                          0.0102502
param_randomforestregressor__max_depth                                                  None  ...                                                  5
param_randomforestregressor__max_features                                           0.859018  ...                                           0.211236
param_randomforestregressor__n_estimators                                                 51  ...                                                193
params                                     {'randomforestregressor__max_depth': None, 'ra...  ...  {'randomforestregressor__max_depth': 5, 'rando...
split0_test_score                                                                  -0.379023  ...                                           -0.49661
split1_test_score                                                                  -0.378697  ...                                          -0.496205
mean_test_score                                                                     -0.37886  ...                                          -0.496408
std_test_score                                                                   0.000163166  ...                                        0.000202858
rank_test_score                                                                            1  ...                                                 50

[13 rows x 50 columns]

In [55]:
# ÎßåÎì§Ïñ¥ÏßÑ Î™®Îç∏ÏóêÏÑú Í∞ÄÏû• ÏÑ±Îä•Ïù¥ Ï¢ãÏùÄ Î™®Îç∏ÏùÑ Î∂àÎü¨ÏòµÎãàÎã§.
pipe = clf.best_estimator_
y_pred = pipe.predict(X_test)
print('ÌõàÎ†® Î™®Îç∏ Ìä∏Î†àÏù¥Îãù Ï†êÏàò', pipe.score(X_train, y_train))
print('Í≤ÄÏ¶ù Î™®Îç∏ Ìä∏Î†àÏù¥Îãù Ï†êÏàò', pipe.score(X_val, y_val))
print('ÌÖåÏä§Ìä∏ Î™®Îç∏ Ìä∏Î†àÏù¥Îãù Ï†êÏàò', pipe.score(X_test, y_test))

ÌõàÎ†® Î™®Îç∏ Ìä∏Î†àÏù¥Îãù Ï†êÏàò 0.9317758139013066
Í≤ÄÏ¶ù Î™®Îç∏ Ìä∏Î†àÏù¥Îãù Ï†êÏàò 0.5293101308997892
ÌÖåÏä§Ìä∏ Î™®Îç∏ Ìä∏Î†àÏù¥Îãù Ï†êÏàò 0.5290458376886824

ÌôïÏã§Ìûà Í≤∞Í≥º Í∞íÏù¥ Ï¢ãÏïÑÏ°åÎã§ !! ÌõàÎ†® Î™®Îç∏Ïóê Ï†ÅÌï©ÎèÑÎ•º Ï¢ÄÎçî Ï§ÑÏó¨Ï£ºÎ©¥ÏÑú Îã§Ïãú ÏãúÎèÑÌï¥Î≥¥ÎäîÍ≤ÉÎèÑ Ï¢ãÏïÑÎ≥¥Ïù∏Îã§!

Îã§Î•∏ Îç∞Ïù¥ÌÑ∞ ÏÖã Í∞ÄÏ†∏ÏôÄÏÑú Ï∂îÍ∞Ä ÏûëÏóÖ ÏßÑÌñâ Ìï¥Î≥¥Í≤†ÏäµÎãàÎã§.